<?php
$deviceName=array(
        "aries&b=F&r=cn&n=" => "小米2/2S",
        "aries_global&b=F&r=global&n=" => "小米2/2S 国际版",
        "cancro&b=F&r=cn&n=" => "小米3/4",
        "cancro_global&b=F&r=global&n=" => "小米3/4 国际版",
        "gemini&b=F&r=cn&n=" => "小米5",
        "gemini_global&b=F&r=global&n=" => "小米5 国际版",
        "capricorn&b=F&r=cn&n=" => "小米5S",
        "capricorn_global&b=F&r=global&n=" => "小米5S 国际版",
        "natrium&b=F&r=cn&n=" => "小米5S Plus",
        "natrium_global&b=F&r=global&n=" => "小米5S Plus 国际版",
        "sagit&b=F&r=cn&n=" => "小米6",
        "wayne&b=F&r=cn&n=" => "小米6X",
        "sagit_global&b=F&r=global&n=" => "小米6 国际版",
        "dipper&b=F&r=cn&n=" => "小米8",
        "dipper_global&b=F&r=global&n=" => "小米8 国际版",
        "dipper_ru_global&b=F&r=global&n=" => "小米8 俄罗斯版",
        "ursa&b=F&r=cn&n=" => "小米8透明探索版",
        "equuleus&b=F&r=cn&n=" => "小米8屏幕指纹版",
        "equuleus_global&b=F&r=global&n=" => "小米8屏幕指纹版 国际版",
        "equuleus_ru_global&b=F&r=ru&n=" => "小米8屏幕指纹版 俄罗斯版",
        "platina&b=F&r=cn&n=" => "小米8青春版",
        "platina_global&b=F&r=global&n=" => "小米8青春版 国际版",
        "platina_ru_global&b=F&r=global&n=" => "小米8青春版 俄罗斯版",
        "sirius&b=F&r=cn&n=" => "小米8 SE",
        "cepheus&b=F&r=cn&n=" => "小米9",
        "cepheus_global&b=F&r=global&n=" => "小米9 国际版",
        "cepheus_eea_global&b=F&r=eea&n=" => "小米9 欧洲EEA版",
        "cepheus_ru_global&b=F&r=global&n=" => "小米9 俄罗斯版",
        "crux&b=F&r=cn&n=" => "小米9 Pro 5G",
        "grus&b=F&r=cn&n=" => "小米9 SE",
        "grus_global&b=F&r=global&n=" => "小米9 SE 国际版",
        "grus_eea_global&b=F&r=eea&n=" => "小米9 SE 欧洲EEA版",
        "grus_ru_global&b=F&r=global&n=" => "小米9 SE 俄罗斯版",
        "pyxis&b=F&r=cn&n=" => "小米CC9/9 Lite",
        "pyxis_global&b=F&r=global&n=" => "小米CC9/9 Lite 国际版",
        "pyxis_eea_global&b=F&r=eea&n=" => "小米CC9/9 Lite 欧洲EEA版",
        "pyxis_ru_global&b=F&r=ru&n=" => "小米CC9/9 Lite 俄罗斯版",
        "davinci&b=F&r=cn&n=" => "Redmi K20",
        "davinci_global&b=F&r=global&n=" => "小米9T/Redmi K20 国际版",
        "davinci_eea_global&b=F&r=eea&n=" => "小米9T/Redmi K20 欧洲EEA版",
        "davinciin_in_global&b=F&r=in&n=" => "小米9T/Redmi K20 印度版",
        "davinci_ru_global&b=F&r=global&n=" => "小米9T/Redmi K20 俄罗斯版",
        "raphael&b=F&r=cn&n=" => "Redmi K20 Pro",
        "raphael_global&b=F&r=global&n=" => "小米9T Pro/Redmi K20 Pro 国际版",
        "raphael_eea_global&b=F&r=eea&n=" => "小米9T Pro/Redmi K20 Pro 欧洲EEA版",
        "raphaelin_in_global&b=F&r=in&n=" => "小米9T Pro/Redmi K20 Pro 印度版",
        "raphael_ru_global&b=F&r=global&n=" => "小米9T Pro/Redmi K20 Pro 俄罗斯版",
        "umi&b=F&r=cn&n=" => "小米10",
        "umi_global&b=F&r=global&n=" => "小米10 国际版",
        "umi_eea_global&b=F&r=eea&n=" => "小米10 欧洲EEA版",
        "umi_in_global&b=F&r=in&n=" => "小米10 印度版",
        "umi_id_global&b=F&r=id&n=" => "小米10 印尼稳定版",
        "umi_ru_global&b=F&r=ru&n=" => "小米10 俄罗斯版",
        "cmi&b=F&r=cn&n=" => "小米10 Pro",
        "cmi_global&b=F&r=global&n=" => "小米10 Pro 国际版",
        "cmi_eea_global&b=F&r=eea&n=" => "小米10 Pro 欧洲EEA版",
        "cmi_in_global&b=F&r=in&n=" => "小米10 Pro 印度版",
        "cmi_ru_global&b=F&r=ru&n=" => "小米10 Pro 俄罗斯版",
        "vangogh&b=F&r=cn&n=" => "小米10 Lite Zoom",
        "vangogh_global&b=F&r=global&n=" => "小米10 Lite Zoom 国际版",
        "vangogh_eea_global&b=F&r=eea&n=" => "小米10 Lite Zoom 欧洲EEA版",
        "vangogh_in_global&b=F&r=in&n=" => "小米10 Lite Zoom 印度版",
        "vangogh_ru_global&b=F&r=ru&n=" => "小米10 Lite Zoom 俄罗斯版",
        "hydrogen_global&b=F&r=global&n=" => "小米Max 国际版",
        "helium_global&b=F&r=global&n=" => "小米Max Prime 国际版",
        "oxygen_global&b=F&r=global&n=" => "小米Max2 国际版",
        "nitrogen&b=F&r=cn&n=" => "小米Max3",
        "nitrogen_global&b=F&r=global&n=" => "小米Max3 国际版",
        "nitrogen_ru_global&b=F&r=global&n=" => "小米Max3 俄罗斯版",
        "scorpio&b=F&r=cn&n=" => "小米Note2",
        "scorpio_global&b=F&r=global&n=" => "小米Note2 国际版",
        "jason&b=F&r=cn&n=" => "小米Note3",
        "jason_global&b=F&r=global&n=" => "小米Note3 国际版",
        "tucana&b=F&r=cn&n=" => "小米CC9 Pro",
        "tucana_global&b=F&r=global&n=" => "小米Note10/CC9 Pro 国际版",
        "tucana_eea_global&b=F&r=eea&n=" => "小米Note10/CC9 Pro 欧洲EEA版",
        "tucana_in_global&b=F&r=in&n=" => "小米Note10/CC9 Pro 印度版",
        "tucana_ru_global&b=F&r=ru&n=" => "小米Note10/CC9 Pro 俄罗斯版",
        "toco&b=F&r=cn&n=" => "小米Note10 Lite",
        "toco_global&b=F&r=global&n=" => "小米Note10 Lite 国际版",
        "toco_eea_global&b=F&r=eea&n=" => "小米Note10 Lite 欧洲EEA版",
        "tocoin_in_global&b=F&r=in&n=" => "小米Note10 Lite 印度版",
        "toco_ru_global&b=F&r=ru&n=" => "小米Note10 Lite 俄罗斯版",
        "lithium_global&b=F&r=global&n=" => "小米MIX 国际版",
        "chiron&b=F&r=cn&n=" => "小米MIX2",
        "chiron_global&b=F&r=global&n=" => "小米MIX2 国际版",
        "polaris&b=F&r=cn&n=" => "小米MIX2S",
        "polaris_global&b=F&r=global&n=" => "小米MIX2S 国际版",
        "polaris_ru_global&b=F&r=global&n=" => "小米MIX2S 俄罗斯版",
        "perseus&b=F&r=cn&n=" => "小米MIX3",
        "perseus_global&b=F&r=global&n=" => "小米MIX3 国际版",
        "perseus_ru_global&b=F&r=global&n=" => "小米MIX3 俄罗斯版",
        "andromeda&b=F&r=cn&n=" => "小米MIX3 5G版",
        "andromeda_global&b=F&r=global&n=" => "小米MIX3 5G版 国际版",
        "andromeda_eea_global&b=F&r=eea&n=" => "小米MIX3 5G版 欧洲EEA版",
        "beryllium_global&b=F&r=global&n=" => "POCO F1 国际版",
        "beryllium_ru_global&b=F&r=global&n=" => "POCO F1 俄罗斯版",
        "lmi_eea_global&b=F&r=eea&n=" => "POCO F2 Pro 欧洲EEA版",
        "phoenixin_in_global&b=F&r=in&n=" => "POCO X2 印度版",
        "rolex&b=F&r=cn&n=" => "红米4A",
        "rolex_global&b=F&r=global&n=" => "红米4A",
        "santoni&b=F&r=cn&n=" => "红米4X",
        "santoni_global&b=F&r=global&n=" => "红米4X 国际版",
        "rosy&b=F&r=cn&n=" => "红米5",
        "rosy_global&b=F&r=global&n=" => "红米5 国际版",
        "rosy_ru_global&b=F&r=global&n=" => "红米5 俄罗斯版",
        "riva&b=F&r=cn&n=" => "红米5A",
        "riva_global&b=F&r=global&n=" => "红米5A 国际版",
        "vince&b=F&r=cn&n=" => "红米5 Plus",
        "vince_global&b=F&r=global&n=" => "红米5 Plus 国际版",
        "cereus&b=F&r=cn&n=" => "红米6",
        "cereus_global&b=F&r=global&n=" => "红米6 国际版",
        "cereus_ru_global&b=F&r=global&n=" => "红米6 国际版",
        "cactus&b=F&r=cn&n=" => "红米6A",
        "cactus_global&b=F&r=global&n=" => "红米6A 国际版",
        "sakura&b=F&r=cn&n=" => "红米6 Pro",
        "sakura_global&b=F&r=global&n=" => "红米6 Pro 国际版",
        "sakura_india_global&b=F&r=in&n=" => "红米6 Pro 印度版",
        "onclite&b=F&r=cn&n=" => "Redmi 7",
        "onclite_global&b=F&r=global&n=" => "Redmi 7 国际版",
        "onclite_eea_global&b=F&r=eea&n" => "Redmi 7 欧洲EEA版",
        "onclite_in_global&b=F&r=in&n=" => "Redmi 7 印度版",
        "onclite_ru_global&b=F&r=global&n=" => "Redmi 7 俄罗斯版",
        "pine&b=F&r=cn&n=" => "Redmi 7A",
        "pine_global&b=F&r=global&n=" => "Redmi 7A 国际版",
        "pine_eea_global&b=F&r=eea&n=" => "Redmi 7A 欧洲EEA版",
        "pine_ru_global&b=F&r=global&n=" => "Redmi 7A 俄罗斯版",
        "olive&b=F&r=cn&n=" => "Redmi 8",
        "olive_global&b=F&r=global&n=" => "Redmi 8 国际版",
        "olive_eea_global&b=F&r=eea&n=" => "Redmi 8 欧洲EEA版",
        "olive_in_global&b=F&r=in&n=" => "Redmi 8 印度版",
        "olive_id_global&b=F&r=global&n=" => "Redmi 8 印尼稳定版",
        "olive_ru_global&b=F&r=ru&n=" => "Redmi 8 俄罗斯版",
        "olivelite&b=F&r=cn&n=" => "Redmi 8A",
        "olivelite_global&b=F&r=global&n=" => "Redmi 8A 国际版",
        "olivelite_eea_global&b=F&r=eea&n=" => "Redmi 8A 欧洲EEA版",
        "olivelite_in_global&b=F&r=in&n==" => "Redmi 8A 印度版",
        "olivelite_id_global&b=F&r=global&n=" => "Redmi 8A 印尼稳定版",
        "olivelite_ru_global&b=F&r=ru&n=" => "Redmi 8A 俄罗斯版",
        "olivewood_global&b=F&r=global&n=" => "Redmi 8A Dual 国际版",
        "olivewood_eea_global&b=F&r=eea&n=" => "Redmi 8A Dual 欧洲EEA版",
        "olivewood_in_global&b=F&r=in&n==" => "Redmi 8A Dual 印度版",
        "olivewood_id_global&b=F&r=global&n=" => "Redmi 8A Dual 印尼稳定版",
        "olivewood_ru_global&b=F&r=ru&n=" => "Redmi 8A Dual 俄罗斯版",
        "ysl&b=F&r=cn&n=" => "红米S2",
        "ysl_global&b=F&r=global&n=" => "红米S2 国际版",
        "ysl_global&b=F&r=in&n=" => "红米S2 印度版",
        "ysl_ru_global&b=F&r=global&n=" => "红米S2 俄罗斯版",
        "onc_in_global&b=F&r=in&n=" => "Redmi Y3 印度版",
        "mido&b=F&r=cn&n=" => "红米Note4X",
        "mido_global&b=F&r=global&n=" => "红米Note4X 国际版",
        "whyred&b=F&r=cn&n=" => "红米Note5",
        "whyred_global&b=F&r=global&n=" => "红米Note5/Pro 国际版",
        "whyred_ru_global&b=F&r=global&n=" => "红米Note5 俄罗斯版",
        "ugglite&b=F&r=cn&n=" => "红米Note5A 标准版",
        "ugglite_global&b=F&r=global&n=" => "红米Note5A 标准版 国际版",
        "ugg&b=F&r=cn&n=" => "红米Note5A 高配版",
        "ugg_global&b=F&r=global&n=" => "红米Note5A 高配版 国际版",
        "tulip_global&b=F&r=global&n=" => "红米Note6 Pro 国际版",
        "tulip_ru_global&b=F&r=ru&n=" => "红米Note6 Pro 俄罗斯版",
        "lavender&b=F&r=cn&n=" => "Redmi Note 7",
        "lavender_global&b=F&r=global&n=" => "Redmi Note 7 国际版",
        "lavender_eea_global&b=F&r=eea&n=" => "Redmi Note 7 欧洲EEA版",
        "lavender_in_global&b=F&r=in&n=" => "Redmi Note 7 印度版",
        "lavender_ru_global&b=F&r=global&n=" => "Redmi Note 7 俄罗斯版",
        "violet&b=F&r=cn&n=" => "Redmi Note 7 Pro",
        "violet_in_global&b=F&r=in&n=" => "Redmi Note 7 Pro 印度版",
        "ginkgo&b=F&r=cn&n=" => "Redmi Note 8",
        "ginkgo_global&b=F&r=global&n=" => "Redmi Note 8 国际版",
        "ginkgo_in_global&b=F&r=in&n=" => "Redmi Note 8 印度版",
        "ginkgo_id_global&b=F&r=global&n=" => "Redmi Note 8 印尼稳定版",
        "willow_global&b=F&r=global&n=" => "Redmi Note 8T 国际版",
        "willow_in_global&b=F&r=in&n=" => "Redmi Note 8T 印度版",
        "willow_eea_global&b=F&r=eea&n=" => "Redmi Note 8T 欧洲EEA版",
        "willow_ru_global&b=F&r=global&n=" => "Redmi Note 8T 俄罗斯版",
        "begonia&b=F&r=cn&n=" => "Redmi Note 8 Pro",
        "begonia_global&b=F&r=global&n=" => "Redmi Note 8 Pro 国际版",
        "begonia_eea_global&b=F&r=eea&n=" => "Redmi Note 8 Pro 欧洲EEA版",
        "begoniain_in_global&b=F&r=in&n=" => "Redmi Note 8 Pro 印度版",
        "begonia_id_global&b=F&r=global&n=" => "Redmi Note 8 Pro 印尼稳定版",
        "begonia_ru_global&b=F&r=ru&n=" => "Redmi Note 8 Pro 俄罗斯版",
        "merlin&b=F&r=cn&n=" => "Redmi Note 9",
        "merlin_global&b=F&r=global&n=" => "Redmi Note 9 国际版",
        "merlin_eea_global&b=F&r=eea&n=" => "Redmi Note 9 欧洲EEA版",
        "curtana&b=F&r=cn&n=" => "Redmi Note 9S",
        "curtana_global&b=F&r=global&n=" => "Redmi Note 9S 国际版",
        "curtana_eea_global&b=F&r=eea&n=" => "Redmi Note 9S 欧洲EEA版",
        "curtana_in_global&b=F&r=in&n=" => "Redmi Note 9S 印度版",
        "curtana_ru_global&b=F&r=ru&n=" => "Redmi Note 9S 俄罗斯版",
        "joyeuse&b=F&r=cn&n=" => "Redmi Note 9 Pro",
        "joyeuse_global&b=F&r=global&n=" => "Redmi Note 9 Pro 国际版",
        "joyeuse_eea_global&b=F&r=eea&n=" => "Redmi Note 9 Pro 欧洲EEA版",
        "joyeuse_id_global&b=F&r=id&n=" => "Redmi Note 9 Pro 印尼稳定版",
        "joyeuse_ru_global&b=F&r=ru&n=" => "Redmi Note 9 Pro 俄罗斯版",
        "excalibur&b=F&r=cn&n=" => "Redmi Note 9 Pro Max",
        "excalibur_global&b=F&r=global&n=" => "Redmi Note 9 Pro Max 国际版",
        "phoenix&b=F&r=cn&n=" => "Redmi K30 4G版",
        "picasso&b=F&r=cn&n=" => "Redmi K30 5G版",
        "lmi&b=F&r=cn&n=" => "Redmi K30 Pro",
    );