<?php
$deviceName = array(
    "aries&b=F&r=cn&n=" => "小米2/2S",
    "aries_global&b=F&r=global&n=" => "小米2/2S 国际版",
    "cancro&b=F&r=cn&n=" => "小米3/4",
    "cancro_global&b=F&r=global&n=" => "小米3/4 国际版",
    "gemini&b=F&r=cn&n=" => "小米5",
    "gemini_global&b=F&r=global&n=" => "小米5 国际版",
    "capricorn&b=F&r=cn&n=" => "小米5S",
    "capricorn_global&b=F&r=global&n=" => "小米5S 国际版",
    "natrium&b=F&r=cn&n=" => "小米5S Plus",
    "natrium_global&b=F&r=global&n=" => "小米5S Plus 国际版",
    "sagit&b=F&r=cn&n=" => "小米6",
    "wayne&b=F&r=cn&n=" => "小米6X",
    "sagit_global&b=F&r=global&n=" => "小米6 国际版",
    "dipper&b=F&r=cn&n=" => "小米8",
    "dipper_global&b=F&r=global&n=" => "小米8 国际版",
    "dipper_ru_global&b=F&r=global&n=" => "小米8 俄罗斯版",
    "ursa&b=F&r=cn&n=" => "小米8透明探索版",
    "equuleus&b=F&r=cn&n=" => "小米8屏幕指纹版",
    "equuleus_global&b=F&r=global&n=" => "小米8屏幕指纹版 国际版",
    "equuleus_ru_global&b=F&r=ru&n=" => "小米8屏幕指纹版 俄罗斯版",
    "platina&b=F&r=cn&n=" => "小米8青春版",
    "platina_global&b=F&r=global&n=" => "小米8青春版 国际版",
    "platina_ru_global&b=F&r=global&n=" => "小米8青春版 俄罗斯版",
    "sirius&b=F&r=cn&n=" => "小米8 SE",
    "cepheus&b=F&r=cn&n=" => "小米9",
    "cepheus_global&b=F&r=global&n=" => "小米9 国际版",
    "cepheus_eea_global&b=F&r=eea&n=" => "小米9 欧洲稳定版",
    "cepheus_ru_global&b=F&r=global&n=" => "小米9 俄罗斯版",
    "crux&b=F&r=cn&n=" => "小米9 Pro 5G",
    "grus&b=F&r=cn&n=" => "小米9 SE",
    "grus_global&b=F&r=global&n=" => "小米9 SE 国际版",
    "grus_eea_global&b=F&r=eea&n=" => "小米9 SE 欧洲稳定版",
    "grus_ru_global&b=F&r=global&n=" => "小米9 SE 俄罗斯版",
    "pyxis&b=F&r=cn&n=" => "小米CC9/9 Lite",
    "pyxis_global&b=F&r=global&n=" => "小米CC9/9 Lite 国际版",
    "pyxis_eea_global&b=F&r=eea&n=" => "小米CC9/9 Lite 欧洲稳定版",
    "pyxis_ru_global&b=F&r=ru&n=" => "小米CC9/9 Lite 俄罗斯版",
    "davinci&b=F&r=cn&n=" => "Redmi K20",
    "davinci_global&b=F&r=global&n=" => "小米9T/Redmi K20 国际版",
    "davinci_eea_global&b=F&r=eea&n=" => "小米9T/Redmi K20 欧洲稳定版",
    "davinciin_in_global&b=F&r=in&n=" => "小米9T/Redmi K20 印度版",
    "davinci_ru_global&b=F&r=global&n=" => "小米9T/Redmi K20 俄罗斯版",
    "raphael&b=F&r=cn&n=" => "Redmi K20 Pro",
    "raphael_global&b=F&r=global&n=" => "小米9T Pro/Redmi K20 Pro 国际版",
    "raphael_eea_global&b=F&r=eea&n=" => "小米9T Pro/Redmi K20 Pro 欧洲稳定版",
    "raphaelin_in_global&b=F&r=in&n=" => "小米9T Pro/Redmi K20 Pro 印度版",
    "raphael_ru_global&b=F&r=global&n=" => "小米9T Pro/Redmi K20 Pro 俄罗斯版",
    "umi&b=F&r=cn&n=" => "小米10",
    "umi_global&b=F&r=global&n=" => "小米10 国际版",
    "umi_eea_global&b=F&r=eea&n=" => "小米10 欧洲稳定版",
    "umi_in_global&b=F&r=in&n=" => "小米10 印度版",
    "umi_id_global&b=F&r=id&n=" => "小米10 印尼稳定版",
    "umi_ru_global&b=F&r=ru&n=" => "小米10 俄罗斯版",
    "cmi&b=F&r=cn&n=" => "小米10 Pro",
    "cmi_global&b=F&r=global&n=" => "小米10 Pro 国际版",
    "cmi_eea_global&b=F&r=eea&n=" => "小米10 Pro 欧洲稳定版",
    "cmi_in_global&b=F&r=in&n=" => "小米10 Pro 印度版",
    "cmi_ru_global&b=F&r=ru&n=" => "小米10 Pro 俄罗斯版",
    "vangogh&b=F&r=cn&n=" => "小米10 Lite Zoom",
    "vangogh_global&b=F&r=global&n=" => "小米10 Lite Zoom 国际版",
    "vangogh_eea_global&b=F&r=eea&n=" => "小米10 Lite Zoom 欧洲稳定版",
    "vangogh_in_global&b=F&r=in&n=" => "小米10 Lite Zoom 印度版",
    "vangogh_ru_global&b=F&r=ru&n=" => "小米10 Lite Zoom 俄罗斯版",
    "hydrogen_global&b=F&r=global&n=" => "小米Max 国际版",
    "helium_global&b=F&r=global&n=" => "小米Max Prime 国际版",
    "oxygen_global&b=F&r=global&n=" => "小米Max2 国际版",
    "nitrogen&b=F&r=cn&n=" => "小米Max3",
    "nitrogen_global&b=F&r=global&n=" => "小米Max3 国际版",
    "nitrogen_ru_global&b=F&r=global&n=" => "小米Max3 俄罗斯版",
    "scorpio&b=F&r=cn&n=" => "小米Note2",
    "scorpio_global&b=F&r=global&n=" => "小米Note2 国际版",
    "jason&b=F&r=cn&n=" => "小米Note3",
    "jason_global&b=F&r=global&n=" => "小米Note3 国际版",
    "tucana&b=F&r=cn&n=" => "小米CC9 Pro",
    "tucana_global&b=F&r=global&n=" => "小米Note10/CC9 Pro 国际版",
    "tucana_eea_global&b=F&r=eea&n=" => "小米Note10/CC9 Pro 欧洲稳定版",
    "tucana_in_global&b=F&r=in&n=" => "小米Note10/CC9 Pro 印度版",
    "tucana_ru_global&b=F&r=ru&n=" => "小米Note10/CC9 Pro 俄罗斯版",
    "toco&b=F&r=cn&n=" => "小米Note10 Lite",
    "toco_global&b=F&r=global&n=" => "小米Note10 Lite 国际版",
    "toco_eea_global&b=F&r=eea&n=" => "小米Note10 Lite 欧洲稳定版",
    "tocoin_in_global&b=F&r=in&n=" => "小米Note10 Lite 印度版",
    "toco_ru_global&b=F&r=ru&n=" => "小米Note10 Lite 俄罗斯版",
    "lithium_global&b=F&r=global&n=" => "小米MIX 国际版",
    "chiron&b=F&r=cn&n=" => "小米MIX2",
    "chiron_global&b=F&r=global&n=" => "小米MIX2 国际版",
    "polaris&b=F&r=cn&n=" => "小米MIX2S",
    "polaris_global&b=F&r=global&n=" => "小米MIX2S 国际版",
    "polaris_ru_global&b=F&r=global&n=" => "小米MIX2S 俄罗斯版",
    "perseus&b=F&r=cn&n=" => "小米MIX3",
    "perseus_global&b=F&r=global&n=" => "小米MIX3 国际版",
    "perseus_ru_global&b=F&r=global&n=" => "小米MIX3 俄罗斯版",
    "andromeda&b=F&r=cn&n=" => "小米MIX3 5G版",
    "andromeda_global&b=F&r=global&n=" => "小米MIX3 5G版 国际版",
    "andromeda_eea_global&b=F&r=eea&n=" => "小米MIX3 5G版 欧洲稳定版",
    "beryllium_global&b=F&r=global&n=" => "POCO F1 国际版",
    "beryllium_ru_global&b=F&r=global&n=" => "POCO F1 俄罗斯版",
    "lmi_eea_global&b=F&r=eea&n=" => "POCO F2 Pro 欧洲稳定版",
    "phoenixin_in_global&b=F&r=in&n=" => "POCO X2 印度版",
    "rolex&b=F&r=cn&n=" => "红米4A",
    "rolex_global&b=F&r=global&n=" => "红米4A",
    "santoni&b=F&r=cn&n=" => "红米4X",
    "santoni_global&b=F&r=global&n=" => "红米4X 国际版",
    "rosy&b=F&r=cn&n=" => "红米5",
    "rosy_global&b=F&r=global&n=" => "红米5 国际版",
    "rosy_ru_global&b=F&r=global&n=" => "红米5 俄罗斯版",
    "riva&b=F&r=cn&n=" => "红米5A",
    "riva_global&b=F&r=global&n=" => "红米5A 国际版",
    "vince&b=F&r=cn&n=" => "红米5 Plus",
    "vince_global&b=F&r=global&n=" => "红米5 Plus 国际版",
    "cereus&b=F&r=cn&n=" => "红米6",
    "cereus_global&b=F&r=global&n=" => "红米6 国际版",
    "cereus_ru_global&b=F&r=global&n=" => "红米6 国际版",
    "cactus&b=F&r=cn&n=" => "红米6A",
    "cactus_global&b=F&r=global&n=" => "红米6A 国际版",
    "cactus_ru_global&b=F&r=global&n=" => "红米6A 俄罗斯版",
    "sakura&b=F&r=cn&n=" => "红米6 Pro",
    "sakura_global&b=F&r=global&n=" => "红米6 Pro 国际版",
    "sakura_india_global&b=F&r=in&n=" => "红米6 Pro 印度版",
    "onclite&b=F&r=cn&n=" => "Redmi 7",
    "onclite_global&b=F&r=global&n=" => "Redmi 7 国际版",
    "onclite_eea_global&b=F&r=eea&n=" => "Redmi 7 欧洲稳定版",
    "onclite_in_global&b=F&r=in&n=" => "Redmi 7 印度版",
    "onclite_ru_global&b=F&r=global&n=" => "Redmi 7 俄罗斯版",
    "pine&b=F&r=cn&n=" => "Redmi 7A",
    "pine_global&b=F&r=global&n=" => "Redmi 7A 国际版",
    "pine_eea_global&b=F&r=eea&n=" => "Redmi 7A 欧洲稳定版",
    "pine_in_global&b=F&r=in&n=" => "Redmi 7A 印度版",
    "pine_ru_global&b=F&r=global&n=" => "Redmi 7A 俄罗斯版",
    "olive&b=F&r=cn&n=" => "Redmi 8",
    "olive_global&b=F&r=global&n=" => "Redmi 8 国际版",
    "olive_eea_global&b=F&r=eea&n=" => "Redmi 8 欧洲稳定版",
    "olive_in_global&b=F&r=in&n=" => "Redmi 8 印度版",
    "olive_id_global&b=F&r=global&n=" => "Redmi 8 印尼稳定版",
    "olive_ru_global&b=F&r=ru&n=" => "Redmi 8 俄罗斯版",
    "olivelite&b=F&r=cn&n=" => "Redmi 8A",
    "olivelite_global&b=F&r=global&n=" => "Redmi 8A 国际版",
    "olivelite_eea_global&b=F&r=eea&n=" => "Redmi 8A 欧洲稳定版",
    "olivelite_in_global&b=F&r=in&n=" => "Redmi 8A 印度版",
    "olivelite_id_global&b=F&r=global&n=" => "Redmi 8A 印尼稳定版",
    "olivelite_ru_global&b=F&r=ru&n=" => "Redmi 8A 俄罗斯版",
    "olivewood_global&b=F&r=global&n=" => "Redmi 8A Dual 国际版",
    "olivewood_eea_global&b=F&r=eea&n=" => "Redmi 8A Dual 欧洲稳定版",
    "olivewood_in_global&b=F&r=in&n=" => "Redmi 8A Dual 印度版",
    "olivewood_id_global&b=F&r=global&n=" => "Redmi 8A Dual 印尼稳定版",
    "olivewood_ru_global&b=F&r=ru&n=" => "Redmi 8A Dual 俄罗斯版",
    "ysl&b=F&r=cn&n=" => "红米S2",
    "ysl_global&b=F&r=global&n=" => "红米S2 国际版",
    "ysl_global&b=F&r=in&n=" => "红米S2 印度版",
    "ysl_ru_global&b=F&r=global&n=" => "红米S2 俄罗斯版",
    "onc_in_global&b=F&r=in&n=" => "Redmi Y3 印度版",
    "mido&b=F&r=cn&n=" => "红米Note4X",
    "mido_global&b=F&r=global&n=" => "红米Note4X 国际版",
    "whyred&b=F&r=cn&n=" => "红米Note5",
    "whyred_global&b=F&r=global&n=" => "红米Note5/Pro 国际版",
    "whyred_ru_global&b=F&r=global&n=" => "红米Note5 俄罗斯版",
    "ugglite&b=F&r=cn&n=" => "红米Note5A 标准版",
    "ugglite_global&b=F&r=global&n=" => "红米Note5A 标准版 国际版",
    "ugg&b=F&r=cn&n=" => "红米Note5A 高配版",
    "ugg_global&b=F&r=global&n=" => "红米Note5A 高配版 国际版",
    "tulip_global&b=F&r=global&n=" => "红米Note6 Pro 国际版",
    "tulip_ru_global&b=F&r=ru&n=" => "红米Note6 Pro 俄罗斯版",
    "lavender&b=F&r=cn&n=" => "Redmi Note 7",
    "lavender_global&b=F&r=global&n=" => "Redmi Note 7 国际版",
    "lavender_eea_global&b=F&r=eea&n=" => "Redmi Note 7 欧洲稳定版",
    "lavender_in_global&b=F&r=in&n=" => "Redmi Note 7 印度版",
    "lavender_ru_global&b=F&r=global&n=" => "Redmi Note 7 俄罗斯版",
    "violet&b=F&r=cn&n=" => "Redmi Note 7 Pro",
    "violet_in_global&b=F&r=in&n=" => "Redmi Note 7 Pro 印度版",
    "ginkgo&b=F&r=cn&n=" => "Redmi Note 8",
    "ginkgo_global&b=F&r=global&n=" => "Redmi Note 8 国际版",
    "ginkgo_in_global&b=F&r=in&n=" => "Redmi Note 8 印度版",
    "ginkgo_id_global&b=F&r=global&n=" => "Redmi Note 8 印尼稳定版",
    "willow_global&b=F&r=global&n=" => "Redmi Note 8T 国际版",
    "willow_in_global&b=F&r=in&n=" => "Redmi Note 8T 印度版",
    "willow_eea_global&b=F&r=eea&n=" => "Redmi Note 8T 欧洲稳定版",
    "willow_ru_global&b=F&r=global&n=" => "Redmi Note 8T 俄罗斯版",
    "begonia&b=F&r=cn&n=" => "Redmi Note 8 Pro",
    "begonia_global&b=F&r=global&n=" => "Redmi Note 8 Pro 国际版",
    "begonia_eea_global&b=F&r=eea&n=" => "Redmi Note 8 Pro 欧洲稳定版",
    "begoniain_in_global&b=F&r=in&n=" => "Redmi Note 8 Pro 印度版",
    "begonia_id_global&b=F&r=global&n=" => "Redmi Note 8 Pro 印尼稳定版",
    "begonia_ru_global&b=F&r=ru&n=" => "Redmi Note 8 Pro 俄罗斯版",
    "merlin&b=F&r=cn&n=" => "Redmi Note 9",
    "merlin_global&b=F&r=global&n=" => "Redmi Note 9 国际版",
    "merlin_eea_global&b=F&r=eea&n=" => "Redmi Note 9 欧洲稳定版",
    "merlin_in_global&b=F&r=in&n=" => "Redmi Note 9 印度版",
    "merlin_id_global&b=F&r=global&n=" => "Redmi Note 9 印尼稳定版",
    "curtana&b=F&r=cn&n=" => "Redmi Note 9S",
    "curtana_global&b=F&r=global&n=" => "Redmi Note 9S 国际版",
    "curtana_eea_global&b=F&r=eea&n=" => "Redmi Note 9S 欧洲稳定版",
    "curtana_in_global&b=F&r=in&n=" => "Redmi Note 9S 印度版",
    "curtana_ru_global&b=F&r=ru&n=" => "Redmi Note 9S 俄罗斯版",
    "joyeuse&b=F&r=cn&n=" => "Redmi Note 9 Pro",
    "joyeuse_global&b=F&r=global&n=" => "Redmi Note 9 Pro 国际版",
    "joyeuse_eea_global&b=F&r=eea&n=" => "Redmi Note 9 Pro 欧洲稳定版",
    "joyeuse_id_global&b=F&r=id&n=" => "Redmi Note 9 Pro 印尼稳定版",
    "joyeuse_ru_global&b=F&r=ru&n=" => "Redmi Note 9 Pro 俄罗斯版",
    "excalibur&b=F&r=cn&n=" => "Redmi Note 9 Pro Max",
    "excalibur_global&b=F&r=global&n=" => "Redmi Note 9 Pro Max 国际版",
    "excalibur_in_global&b=F&r=in&n=" => "Redmi Note 9 Pro Max 印度版",
    "phoenix&b=F&r=cn&n=" => "Redmi K30 4G版",
    "picasso&b=F&r=cn&n=" => "Redmi K30 5G版",
    "lmi&b=F&r=cn&n=" => "Redmi K30 Pro",
    "angelica&b=F&r=cn&n=" => "未知机型",
    "atom&b=F&r=cn&n=" => "未知机型",
    "bomp&b=F&r=cn&n=" => "未知机型",
    "cattail&b=F&r=cn&n=" => "未知机型",
    "dandelion&b=F&r=cn&n=" => "未知机型",
    "draco&b=F&r=cn&n=" => "未知机型",
    "durandal&b=F&r=cn&n=" => "未知机型",
    "galahad&b=F&r=cn&n=" => "未知机型",
    "gram&b=F&r=cn&n=" => "未知机型",
    "hercules&b=F&r=cn&n=" => "未知机型",
    "lancelot&b=F&r=cn&n=" => "未知机型",
    "lmipro&b=F&r=cn&n=" => "未知机型",
    "monet&b=F&r=cn&n=" => "未知机型",
);
$cnDevices = array(
    "sagit&b=F&r=cn&n=",
    "wayne&b=F&r=cn&n=",
    "dipper&b=F&r=cn&n=",
    "equuleus&b=F&r=cn&n=",
    "ursa&b=F&r=cn&n=",
    "platina&b=F&r=cn&n=",
    "sirius&b=F&r=cn&n=",
    "cepheus&b=F&r=cn&n=",
    "crux&b=F&r=cn&n=",
    "grus&b=F&r=cn&n=",
    "pyxis&b=F&r=cn&n=",
    "davinci&b=F&r=cn&n=",
    "raphael&b=F&r=cn&n=",
    "umi&b=F&r=cn&n=",
    "cmi&b=F&r=cn&n=",
    "vangogh&b=F&r=cn&n=",
    "nitrogen&b=F&r=cn&n=",
    "jason&b=F&r=cn&n=",
    "tucana&b=F&r=cn&n=",
    "toco&b=F&r=cn&n=",
    "chiron&b=F&r=cn&n=",
    "polaris&b=F&r=cn&n=",
    "perseus&b=F&r=cn&n=",
    "andromeda&b=F&r=cn&n=",
    "cereus&b=F&r=cn&n=",
    "cactus&b=F&r=cn&n=",
    "sakura&b=F&r=cn&n=",
    "onclite&b=F&r=cn&n=",
    "pine&b=F&r=cn&n=",
    "olive&b=F&r=cn&n=",
    "olivelite&b=F&r=cn&n=",
    "olivewood&b=F&r=cn&n=",
    "whyred&b=F&r=cn&n=",
    "lavender&b=F&r=cn&n=",
    "violet&b=F&r=cn&n=",
    "ginkgo&b=F&r=cn&n=",
    "begonia&b=F&r=cn&n=",
    "merlin&b=F&r=cn&n=",
    "curtana&b=F&r=cn&n=",
    "joyeuse&b=F&r=cn&n=",
    "excalibur&b=F&r=cn&n=",
    "phoenix&b=F&r=cn&n=",
    "picasso&b=F&r=cn&n=",
    "lmi&b=F&r=cn&n=",
    "angelica&b=F&r=cn&n=",
    "atom&b=F&r=cn&n=",
    "bomp&b=F&r=cn&n=",
    "cattail&b=F&r=cn&n=",
    "dandelion&b=F&r=cn&n=",
    "draco&b=F&r=cn&n=",
    "durandal&b=F&r=cn&n=",
    "galahad&b=F&r=cn&n=",
    "gram&b=F&r=cn&n=",
    "hercules&b=F&r=cn&n=",
    "lancelot&b=F&r=cn&n=",
    "lmipro&b=F&r=cn&n=",
    "monet&b=F&r=cn&n=",
);
$gbDevices = array(
    "sagit_global&b=F&r=global&n=",
    "dipper_global&b=F&r=global&n=",
    "dipper_ru_global&b=F&r=global&n=",
    "equuleus_global&b=F&r=global&n=",
    "equuleus_ru_global&b=F&r=ru&n=",
    "platina_global&b=F&r=global&n=",
    "platina_ru_global&b=F&r=global&n=",
    "cepheus_global&b=F&r=global&n=",
    "cepheus_eea_global&b=F&r=eea&n=",
    "cepheus_ru_global&b=F&r=global&n=",
    "grus_global&b=F&r=global&n=",
    "grus_eea_global&b=F&r=eea&n=",
    "grus_ru_global&b=F&r=global&n=",
    "pyxis_global&b=F&r=global&n=",
    "pyxis_eea_global&b=F&r=eea&n=",
    "pyxis_ru_global&b=F&r=ru&n=",
    "davinci_global&b=F&r=global&n=",
    "davinci_eea_global&b=F&r=eea&n=",
    "davinciin_in_global&b=F&r=in&n=",
    "davinci_ru_global&b=F&r=global&n=",
    "raphael_global&b=F&r=global&n=",
    "raphael_eea_global&b=F&r=eea&n=",
    "raphaelin_in_global&b=F&r=in&n=",
    "raphael_ru_global&b=F&r=global&n=",
    "umi_global&b=F&r=global&n=",
    "umi_eea_global&b=F&r=eea&n=",
    "umi_in_global&b=F&r=in&n=",
    "umi_id_global&b=F&r=id&n=",
    "umi_ru_global&b=F&r=ru&n=",
    "cmi_global&b=F&r=global&n=",
    "cmi_eea_global&b=F&r=eea&n=",
    "cmi_in_global&b=F&r=in&n=",
    "cmi_ru_global&b=F&r=ru&n=",
    "vangogh_global&b=F&r=global&n=",
    "vangogh_eea_global&b=F&r=eea&n=",
    "vangogh_in_global&b=F&r=in&n=",
    "vangogh_ru_global&b=F&r=ru&n=",
    "hydrogen_global&b=F&r=global&n=",
    "helium_global&b=F&r=global&n=",
    "oxygen_global&b=F&r=global&n=",
    "nitrogen_global&b=F&r=global&n=",
    "nitrogen_ru_global&b=F&r=global&n=",
    "jason_global&b=F&r=global&n=",
    "tucana_global&b=F&r=global&n=",
    "tucana_eea_global&b=F&r=eea&n=",
    "tucana_in_global&b=F&r=in&n=",
    "tucana_ru_global&b=F&r=ru&n=",
    "toco_global&b=F&r=global&n=",
    "toco_eea_global&b=F&r=eea&n=",
    "tocoin_in_global&b=F&r=in&n=",
    "toco_ru_global&b=F&r=ru&n=",
    "chiron_global&b=F&r=global&n=",
    "polaris_global&b=F&r=global&n=",
    "polaris_ru_global&b=F&r=global&n=",
    "perseus_global&b=F&r=global&n=",
    "perseus_ru_global&b=F&r=global&n=",
    "andromeda_global&b=F&r=global&n=",
    "andromeda_eea_global&b=F&r=eea&n=",
    "beryllium_global&b=F&r=global&n=",
    "beryllium_ru_global&b=F&r=global&n=",
    "lmi_eea_global&b=F&r=eea&n=",
    "phoenixin_in_global&b=F&r=in&n=",
    "cereus_global&b=F&r=global&n=",
    "cereus_ru_global&b=F&r=global&n=",
    "cactus_global&b=F&r=global&n=",
    "cactus_ru_global&b=F&r=global&n=",
    "sakura_global&b=F&r=global&n=",
    "sakura_india_global&b=F&r=in&n=",
    "onclite_global&b=F&r=global&n=",
    "onclite_eea_global&b=F&r=eea&n=",
    "onclite_in_global&b=F&r=in&n=",
    "onclite_ru_global&b=F&r=global&n=",
    "pine_global&b=F&r=global&n=",
    "pine_eea_global&b=F&r=eea&n=",
    "pine_in_global&b=F&r=in&n=",
    "pine_ru_global&b=F&r=global&n=",
    "olive_global&b=F&r=global&n=",
    "olive_eea_global&b=F&r=eea&n=",
    "olive_in_global&b=F&r=in&n=",
    "olive_id_global&b=F&r=global&n=",
    "olive_ru_global&b=F&r=ru&n=",
    "olivelite_global&b=F&r=global&n=",
    "olivelite_eea_global&b=F&r=eea&n=",
    "olivelite_in_global&b=F&r=in&n=",
    "olivelite_id_global&b=F&r=global&n=",
    "olivelite_ru_global&b=F&r=ru&n=",
    "olivewood_global&b=F&r=global&n=",
    "olivewood_eea_global&b=F&r=eea&n=",
    "olivewood_in_global&b=F&r=in&n=",
    "olivewood_id_global&b=F&r=global&n=",
    "olivewood_ru_global&b=F&r=ru&n=",
    "ysl_global&b=F&r=global&n=",
    "ysl_global&b=F&r=in&n=",
    "ysl_ru_global&b=F&r=global&n=",
    "onc_in_global&b=F&r=in&n=",
    "whyred_global&b=F&r=global&n=",
    "whyred_ru_global&b=F&r=global&n=",
    "tulip_global&b=F&r=global&n=",
    "tulip_ru_global&b=F&r=ru&n=",
    "lavender_global&b=F&r=global&n=",
    "lavender_eea_global&b=F&r=eea&n=",
    "lavender_in_global&b=F&r=in&n=",
    "lavender_ru_global&b=F&r=global&n=",
    "violet_in_global&b=F&r=in&n=",
    "ginkgo_global&b=F&r=global&n=",
    "ginkgo_in_global&b=F&r=in&n=",
    "ginkgo_id_global&b=F&r=global&n=",
    "willow_global&b=F&r=global&n=",
    "willow_in_global&b=F&r=in&n=",
    "willow_eea_global&b=F&r=eea&n=",
    "willow_ru_global&b=F&r=global&n=",
    "begonia_global&b=F&r=global&n=",
    "begonia_eea_global&b=F&r=eea&n=",
    "begoniain_in_global&b=F&r=in&n=",
    "begonia_id_global&b=F&r=global&n=",
    "begonia_ru_global&b=F&r=ru&n=",
    "merlin_global&b=F&r=global&n=",
    "merlin_eea_global&b=F&r=eea&n=",
    "merlin_in_global&b=F&r=in&n=",
    "merlin_id_global&b=F&r=global&n=",
    "curtana_global&b=F&r=global&n=",
    "curtana_eea_global&b=F&r=eea&n=",
    "curtana_in_global&b=F&r=in&n=",
    "curtana_ru_global&b=F&r=ru&n=",
    "joyeuse_global&b=F&r=global&n=",
    "joyeuse_eea_global&b=F&r=eea&n=",
    "joyeuse_id_global&b=F&r=id&n=",
    "joyeuse_ru_global&b=F&r=ru&n=",
    "excalibur_global&b=F&r=global&n=",
    "excalibur_in_global&b=F&r=in&n=",
);

$cnCurrent = array(
    "sagit&b=F&r=cn&n=" => "V11.0.5.0.PCACNXM",
    "wayne&b=F&r=cn&n=" => "V11.0.6.0.PDCCNXM",
    "dipper&b=F&r=cn&n=" => "V11.0.7.0.QEACNXM",
    "equuleus&b=F&r=cn&n=" => "V11.0.2.0.QECCNXM",
    "ursa&b=F&r=cn&n=" => "V11.0.3.0.QEHCNXM",
    "platina&b=F&r=cn&n=" => "V11.0.2.0.QDTCNXM",
    "sirius&b=F&r=cn&n=" => "V11.0.2.0.QEBCNXM",
    "cepheus&b=F&r=cn&n=" => "V11.0.9.0.QFACNXM",
    "crux&b=F&r=cn&n=" => "V11.0.3.0.PFXCNXM",
    "grus&b=F&r=cn&n=" => "V11.0.3.0.QFBCNXM",
    "pyxis&b=F&r=cn&n=" => "V11.0.3.0.QFCCNXM",
    "davinci&b=F&r=cn&n=" => "V11.0.6.0.QFJCNXM",
    "raphael&b=F&r=cn&n=" => "V11.0.8.0.QFKCNXM",
    "umi&b=F&r=cn&n=" => "V11.0.24.0.QJBCNXM",
    "cmi&b=F&r=cn&n=" => "V11.0.17.0.QJACNXM",
    "vangogh&b=F&r=cn&n=" => "V11.0.6.0.QJVCNXM",
    "nitrogen&b=F&r=cn&n=" => "V11.0.4.0.QEDCNXM",
    "jason&b=F&r=cn&n=" => "V11.0.4.0.PCHCNXM",
    "tucana&b=F&r=cn&n=" => "V11.1.2.0.QFDCNXM",
    "toco&b=F&r=cn&n=" => "",
    "chiron&b=F&r=cn&n=" => "V11.0.5.0.PDECNXM",
    "polaris&b=F&r=cn&n=" => "V11.0.3.0.QDGCNXM",
    "perseus&b=F&r=cn&n=" => "V11.0.2.0.QEECNXM",
    "andromeda&b=F&r=cn&n=" => "V10.3.17.0.PEMCNXM",
    "cereus&b=F&r=cn&n=" => "V11.0.4.0.PCGCNXM",
    "cactus&b=F&r=cn&n=" => "V11.0.5.0.PCBCNXM",
    "sakura&b=F&r=cn&n=" => "V11.0.5.0.PDICNXM",
    "onclite&b=F&r=cn&n=" => "V11.0.4.0.PFLCNXM",
    "pine&b=F&r=cn&n=" => "V11.0.6.0.PCMCNXM",
    "olive&b=F&r=cn&n=" => "V11.0.10.0.PCNCNXM",
    "olivelite&b=F&r=cn&n=" => "V11.0.9.0.PCPCNXM",
    "olivewood&b=F&r=cn&n=" => "",
    "whyred&b=F&r=cn&n=" => "V11.0.2.0.PEICNXM",
    "lavender&b=F&r=cn&n=" => "V11.0.7.0.PFGCNXM",
    "violet&b=F&r=cn&n=" => "V11.0.8.0.PFHCNXM",
    "ginkgo&b=F&r=cn&n=" => "V11.0.6.0.PCOCNXM",
    "begonia&b=F&r=cn&n=" => "V11.0.3.0.PGGCNXM",
    "merlin&b=F&r=cn&n=" => "V11.0.3.0.QJOCNXM",
    "curtana&b=F&r=cn&n=" => "",
    "joyeuse&b=F&r=cn&n=" => "",
    "excalibur&b=F&r=cn&n=" => "",
    "phoenix&b=F&r=cn&n=" => "V11.0.15.0.QGHCNXM",
    "picasso&b=F&r=cn&n=" => "V11.1.25.0.QGICNXM",
    "lmi&b=F&r=cn&n=" => "V11.0.16.0.QJKCNXM",
    "angelica&b=F&r=cn&n=" => "",
    "atom&b=F&r=cn&n=" => "",
    "bomp&b=F&r=cn&n=" => "",
    "cattail&b=F&r=cn&n=" => "",
    "dandelion&b=F&r=cn&n=" => "",
    "draco&b=F&r=cn&n=" => "",
    "durandal&b=F&r=cn&n=" => "",
    "galahad&b=F&r=cn&n=" => "",
    "gram&b=F&r=cn&n=" => "",
    "hercules&b=F&r=cn&n=" => "",
    "lancelot&b=F&r=cn&n=" => "",
    "lmipro&b=F&r=cn&n=" => "",
    "monet&b=F&r=cn&n=" => "",
);

$gbCurrent = array(
    "sagit_global&b=F&r=global&n=" => "V11.0.6.0.PCAMIXM",
    "dipper_global&b=F&r=global&n=" => "V11.0.4.0.QEAMIXM",
    "dipper_ru_global&b=F&r=global&n=" => "V11.0.2.0.QEARUXM",
    "equuleus_global&b=F&r=global&n=" => "V11.0.5.0.QECMIXM",
    "equuleus_ru_global&b=F&r=ru&n=" => "V11.0.1.0.QECRUXM",
    "platina_global&b=F&r=global&n=" => "V11.0.1.0.QDTMIXM",
    "platina_ru_global&b=F&r=global&n=" => "V11.0.1.0.QDTRUXM",
    "cepheus_global&b=F&r=global&n=" => "V11.0.6.0.QFAMIXM",
    "cepheus_eea_global&b=F&r=eea&n=" => "V11.0.9.0.QFAEUXM",
    "cepheus_ru_global&b=F&r=global&n=" => "V11.0.4.0.QFARUXM",
    "grus_global&b=F&r=global&n=" => "V11.0.2.0.QFBMIXM",
    "grus_eea_global&b=F&r=eea&n=" => "V11.0.2.0.QFBEUXM",
    "grus_ru_global&b=F&r=global&n=" => "V11.0.2.0.QFBRUXM",
    "pyxis_global&b=F&r=global&n=" => "V11.0.1.0.QFCMIXM",
    "pyxis_eea_global&b=F&r=eea&n=" => "V11.0.1.0.QFCEUXM",
    "pyxis_ru_global&b=F&r=ru&n=" => "V11.0.1.0.QFCRUXM",
    "davinci_global&b=F&r=global&n=" => "V11.0.5.0.QFJMIXM",
    "davinci_eea_global&b=F&r=eea&n=" => "V11.0.5.0.QFJEUXM",
    "davinciin_in_global&b=F&r=in&n=" => "V11.0.3.0.QFJINXM",
    "davinci_ru_global&b=F&r=global&n=" => "V11.0.5.0.QFJRUXM",
    "raphael_global&b=F&r=global&n=" => "V11.0.4.0.QFKMIXM",
    "raphael_eea_global&b=F&r=eea&n=" => "V11.0.6.0.QFKEUXM",
    "raphaelin_in_global&b=F&r=in&n=" => "V11.0.4.0.QFKINXM",
    "raphael_ru_global&b=F&r=global&n=" => "V11.0.2.0.QFKRUXM",
    "umi_global&b=F&r=global&n=" => "V11.0.2.0.QJBMIXM",
    "umi_eea_global&b=F&r=eea&n=" => "V11.0.13.0.QJBEUXM",
    "umi_in_global&b=F&r=in&n=" => "V11.0.4.0.QJBINXM",
    "umi_id_global&b=F&r=id&n=" => "",
    "umi_ru_global&b=F&r=ru&n=" => "",
    "cmi_global&b=F&r=global&n=" => "",
    "cmi_eea_global&b=F&r=eea&n=" => "V11.0.10.0.QJAEUXM",
    "cmi_in_global&b=F&r=in&n=" => "",
    "cmi_ru_global&b=F&r=ru&n=" => "",
    "vangogh_global&b=F&r=global&n=" => "",
    "vangogh_eea_global&b=F&r=eea&n=" => "",
    "vangogh_in_global&b=F&r=in&n=" => "",
    "vangogh_ru_global&b=F&r=ru&n=" => "",
    "hydrogen_global&b=F&r=global&n=" => "V10.2.2.0.NBCMIXM",
    "helium_global&b=F&r=global&n=" => "V10.2.2.0.NBDMIXM",
    "oxygen_global&b=F&r=global&n=" => "V11.0.2.0.NDDMIXM",
    "nitrogen_global&b=F&r=global&n=" => "V11.0.1.0.QEDMIXM",
    "nitrogen_ru_global&b=F&r=global&n=" => "V11.0.1.0.QEDRUXM",
    "jason_global&b=F&r=global&n=" => "V11.0.5.0.PCHMIXM",
    "tucana_global&b=F&r=global&n=" => "V11.0.9.0.PFDMIXM",
    "tucana_eea_global&b=F&r=eea&n=" => "V11.0.16.0.PFDEUXM",
    "tucana_in_global&b=F&r=in&n=" => "",
    "tucana_ru_global&b=F&r=ru&n=" => "V11.0.8.0.PFDRUXM",
    "toco_global&b=F&r=global&n=" => "V11.0.1.0.QFNMIXM",
    "toco_eea_global&b=F&r=eea&n=" => "V11.0.7.0.QFNEUXM",
    "tocoin_in_global&b=F&r=in&n=" => "",
    "toco_ru_global&b=F&r=ru&n=" => "V11.0.1.0.QFNRUXM",
    "chiron_global&b=F&r=global&n=" => "V11.0.6.0.PDEMIXM",
    "polaris_global&b=F&r=global&n=" => "V11.0.4.0.QDGMIXM",
    "polaris_ru_global&b=F&r=global&n=" => "V11.0.1.0.QDGRUXM",
    "perseus_global&b=F&r=global&n=" => "V11.0.3.0.QEEMIXM",
    "perseus_ru_global&b=F&r=global&n=" => "V11.0.3.0.QEERUXM",
    "andromeda_global&b=F&r=global&n=" => "V10.3.19.0.PEMMIXM",
    "andromeda_eea_global&b=F&r=eea&n=" => "V10.3.23.0.PEMEUXM",
    "beryllium_global&b=F&r=global&n=" => "V11.0.8.0.QEJMIXM",
    "beryllium_ru_global&b=F&r=global&n=" => "V11.0.2.0.QEJRUXM",
    "lmi_eea_global&b=F&r=eea&n=" => "V11.0.6.0.QJKEUXM",
    "phoenixin_in_global&b=F&r=in&n=" => "V11.0.7.0.QGHINXM",
    "cereus_global&b=F&r=global&n=" => "V11.0.3.0.PCGMIXM",
    "cereus_ru_global&b=F&r=global&n=" => "V11.0.3.0.PCGRUXM",
    "cactus_global&b=F&r=global&n=" => "V11.0.8.0.PCBMIXM",
    "cactus_ru_global&b=F&r=global&n=" => "V11.0.3.0.PCBRUXM",
    "sakura_global&b=F&r=global&n=" => "",
    "sakura_india_global&b=F&r=in&n=" => "V11.0.6.0.PDMMIXM",
    "onclite_global&b=F&r=global&n=" => "V11.0.5.0.PFLMIXM",
    "onclite_eea_global&b=F&r=eea&n=" => "V11.0.6.0.PFLEUXM",
    "onclite_in_global&b=F&r=in&n=" => "V11.0.6.0.PFLINXM",
    "onclite_ru_global&b=F&r=global&n=" => "V11.0.5.0.PFLRUXM",
    "pine_global&b=F&r=global&n=" => "V11.0.7.0.PCMMIXM",
    "pine_eea_global&b=F&r=eea&n=" => "V11.0.18.0.PCMEUXM",
    "pine_in_global&b=F&r=in&n=" => "V11.0.5.0.PCMINXM",
    "pine_ru_global&b=F&r=global&n=" => "V11.0.6.0.PCMRUXM",
    "olive_global&b=F&r=global&n=" => "V11.0.10.0.PCNMIXM",
    "olive_eea_global&b=F&r=eea&n=" => "V11.0.6.0.PCNEUXM",
    "olive_in_global&b=F&r=in&n=" => "V11.0.10.0.PCNINXM",
    "olive_id_global&b=F&r=global&n=" => "V11.0.5.0.PCNIDXM",
    "olive_ru_global&b=F&r=ru&n=" => "V11.0.5.0.PCNRUXM",
    "olivelite_global&b=F&r=global&n=" => "V11.0.6.0.PCPMIXM",
    "olivelite_eea_global&b=F&r=eea&n=" => "V11.0.4.0.PCPEUXM",
    "olivelite_in_global&b=F&r=in&n=" => "V11.0.8.0.PCPINXM",
    "olivelite_id_global&b=F&r=global&n=" => "V11.0.4.0.PCPIDXM",
    "olivelite_ru_global&b=F&r=ru&n=" => "V11.0.4.0.PCPRUXM",
    "olivewood_global&b=F&r=global&n=" => "",
    "olivewood_eea_global&b=F&r=eea&n=" => "",
    "olivewood_in_global&b=F&r=in&n=" => "V11.0.6.0.PCQINXM",
    "olivewood_id_global&b=F&r=global&n=" => "V11.0.3.0.PCQIDXM",
    "olivewood_ru_global&b=F&r=ru&n=" => "",
    "ysl_global&b=F&r=global&n=" => "V11.0.5.0.PEFMIXM",
    "ysl_global&b=F&r=in&n=" => "V10.2.1.0.OEFMIXM",
    "ysl_ru_global&b=F&r=global&n=" => "V11.0.1.0.PEFRUXM",
    "onc_in_global&b=F&r=in&n=" => "V11.0.9.0.PFFINXM",
    "whyred_global&b=F&r=global&n=" => "V11.0.3.0.PEIMIXM",
    "whyred_ru_global&b=F&r=global&n=" => "V11.0.1.0.PEIRUXM",
    "tulip_global&b=F&r=global&n=" => "V11.0.4.0.PEKMIXM",
    "tulip_ru_global&b=F&r=ru&n=" => "V10.2.1.0.OEKRUXM",
    "lavender_global&b=F&r=global&n=" => "V11.0.6.0.PFGMIXM",
    "lavender_eea_global&b=F&r=eea&n=" => "V11.0.8.0.PFGEUXM",
    "lavender_in_global&b=F&r=in&n=" => "V11.0.9.0.PFGINXM",
    "lavender_ru_global&b=F&r=global&n=" => "V11.0.9.0.PFGRUXM",
    "violet_in_global&b=F&r=in&n=" => "V11.0.9.0.PFHINXM",
    "ginkgo_global&b=F&r=global&n=" => "V11.0.8.0.PCOMIXM",
    "ginkgo_in_global&b=F&r=in&n=" => "V11.0.4.0.PCOINXM",
    "ginkgo_id_global&b=F&r=global&n=" => "V11.0.4.0.PCOIDXM",
    "willow_global&b=F&r=global&n=" => "V11.0.3.0.PCXMIXM",
    "willow_in_global&b=F&r=in&n=" => "",
    "willow_eea_global&b=F&r=eea&n=" => "V11.0.7.0.PCXEUXM",
    "willow_ru_global&b=F&r=global&n=" => "V11.0.3.0.PCXRUXM",
    "begonia_global&b=F&r=global&n=" => "V11.0.6.0.PGGMIXM",
    "begonia_eea_global&b=F&r=eea&n=" => "V11.0.3.0.PGGEUXM",
    "begoniain_in_global&b=F&r=in&n=" => "V11.0.4.0.PGGINXM",
    "begonia_id_global&b=F&r=global&n=" => "V11.0.2.0.PGGIDXM",
    "begonia_ru_global&b=F&r=ru&n=" => "V11.0.3.0.PGGRUXM",
    "merlin_global&b=F&r=global&n=" => "V11.0.2.0.QJOMIXM",
    "merlin_eea_global&b=F&r=eea&n=" => "V11.0.3.0.QJOEUXM",
    "merlin_in_global&b=F&r=in&n=" => "",
    "merlin_id_global&b=F&r=global&n=" => "V11.0.1.0.QJOIDXM",
    "curtana_global&b=F&r=global&n=" => "V11.0.8.0.QJWMIXM",
    "curtana_eea_global&b=F&r=eea&n=" => "V11.0.2.0.QJWEUXM",
    "curtana_in_global&b=F&r=in&n=" => "V11.0.6.0.QJWINXM",
    "curtana_ru_global&b=F&r=ru&n=" => "V11.0.2.0.QJWRUXM",
    "joyeuse_global&b=F&r=global&n=" => "V11.0.1.0.QJZMIXM",
    "joyeuse_eea_global&b=F&r=eea&n=" => "V11.0.1.0.QJZEUXM",
    "joyeuse_id_global&b=F&r=id&n=" => "V11.0.1.0.QJZIDXM",
    "joyeuse_ru_global&b=F&r=ru&n=" => "",
    "excalibur_global&b=F&r=global&n=" => "",
    "excalibur_in_global&b=F&r=in&n=" => "V11.0.2.0.QJXINXM",
);